"""Добавлены таблицы Order и OrderItem_1

Revision ID: 0212ed9fadc3
Revises: 80cb4ad10d86
Create Date: 2025-11-19 22:25:09.885477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0212ed9fadc3'
down_revision: Union[str, Sequence[str], None] = '80cb4ad10d86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
