"""Добавлены unique и index столбцам slug

Revision ID: 1907bbbd1385
Revises: 60650e914c8b
Create Date: 2026-01-11 23:06:58.655262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1907bbbd1385'
down_revision: Union[str, Sequence[str], None] = '60650e914c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_sub_categories_slug'), 'sub_categories', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_categories_slug'), table_name='sub_categories')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    # ### end Alembic commands ###
