"""Добавлены таблицы Order и OrderItem_3

Revision ID: 1d4b25c62e88
Revises: 8df520951afd
Create Date: 2025-11-21 23:47:19.655199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4b25c62e88'
down_revision: Union[str, Sequence[str], None] = '8df520951afd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
