"""order, shipping_adrees, nullable=True

Revision ID: 2c8af39ec5e9
Revises: e3cfd9144b68
Create Date: 2025-11-23 19:35:56.949333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8af39ec5e9'
down_revision: Union[str, Sequence[str], None] = 'e3cfd9144b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'shipping_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
