"""Добавлен slug_2

Revision ID: 32eb11e8416e
Revises: 65072b61cf60
Create Date: 2025-11-14 20:39:19.005711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32eb11e8416e'
down_revision: Union[str, Sequence[str], None] = '65072b61cf60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'slug',
               existing_type=sa.TEXT(),
               server_default=None,
               nullable=False)
    op.alter_column('products', 'slug',
               existing_type=sa.TEXT(),
               server_default=None,
               nullable=False)
    op.alter_column('sub_categories', 'slug',
               existing_type=sa.TEXT(),
               server_default=None,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_categories', 'slug',
               existing_type=sa.TEXT(),
               server_default=sa.text("'slug don''t exist'::text"),
               nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.TEXT(),
               server_default=sa.text("'slug don''t exist'::text"),
               nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.TEXT(),
               server_default=sa.text("'slug don''t exist'::text"),
               nullable=True)
    # ### end Alembic commands ###
