"""В таблоице SubCategory добавлен столбец picture

Revision ID: 4756233f7abf
Revises: 
Create Date: 2025-11-05 20:28:10.033995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4756233f7abf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    if op.get_bind().execute(
            sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='sub_categories' AND column_name='picture")).scalar() is None:
        op.add_column('sub_categories', sa.Column('picture', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_categories', 'picture')
    # ### end Alembic commands ###
