"""Фото категории и подкатегории теперь обязательно

Revision ID: 56c30caaee02
Revises: 4756233f7abf
Create Date: 2025-11-05 20:35:54.084448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c30caaee02'
down_revision: Union[str, Sequence[str], None] = '4756233f7abf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'picture',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sub_categories', 'picture',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_categories', 'picture',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('categories', 'picture',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
