"""Добавлен slug_1

Revision ID: 65072b61cf60
Revises: 893d5484db41
Create Date: 2025-11-14 20:37:17.914817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65072b61cf60'
down_revision: Union[str, Sequence[str], None] = '893d5484db41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'slug',
               existing_type=sa.TEXT(),
               server_default="slug don't exist",
               existing_nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.TEXT(),
               server_default="slug don't exist",
               existing_nullable=True)
    op.alter_column('sub_categories', 'slug',
               existing_type=sa.TEXT(),
               server_default="slug don't exist",
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sub_categories', 'slug',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('categories', 'slug',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
