"""Добавлено описание в products_2

Revision ID: 69e7c97f9cc8
Revises: b9d3e3f53f0b
Create Date: 2025-11-10 19:54:18.280072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69e7c97f9cc8'
down_revision: Union[str, Sequence[str], None] = 'b9d3e3f53f0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               server_default=sa.text("'default_description'::text"),
               existing_nullable=False)
    # ### end Alembic commands ###
