"""Добавлен slug

Revision ID: 893d5484db41
Revises: 69e7c97f9cc8
Create Date: 2025-11-14 20:34:25.370446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '893d5484db41'
down_revision: Union[str, Sequence[str], None] = '69e7c97f9cc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('slug', sa.Text(), nullable=True))
    op.add_column('products', sa.Column('slug', sa.Text(), nullable=True))
    op.add_column('sub_categories', sa.Column('slug', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_categories', 'slug')
    op.drop_column('products', 'slug')
    op.drop_column('categories', 'slug')
    # ### end Alembic commands ###
