"""Добавлен столбец is_active в таблицу users

Revision ID: a9f6eb4e0dd4
Revises: 1907bbbd1385
Create Date: 2026-01-25 13:00:09.673438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9f6eb4e0dd4'
down_revision: Union[str, Sequence[str], None] = '1907bbbd1385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # 2. Заполняем все существующие записи значением True
    op.execute(
        "UPDATE users SET is_active = TRUE WHERE is_active IS NULL"
    )

    # 3. Делаем столбец NOT NULL
    op.alter_column('users', 'is_active',
                    existing_type=sa.Boolean(),
                    nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
