"""Добавлены таблицы Order и OrderItem_2

Revision ID: c0b7d42ae030
Revises: 0212ed9fadc3
Create Date: 2025-11-19 22:26:32.539657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0b7d42ae030'
down_revision: Union[str, Sequence[str], None] = '0212ed9fadc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
